import pandas as pd
from itertools import combinations
import glob, os
from pathlib import Path

configfile: "config.yaml"

## --------------------------------------------------------------------------------
## global parameters from config file

REF_GENOME = config["ref_genome"] ## path to reference genomes in .fasta format
PREFIX = config["prefix"] ## prefix for output files
MQ = config["MQ"] ## minimum mapping quality

# We use paths relative to the project root dir here if paths are relative,
# accounting for them either being in the working dir (perferred), or in the
# source dir if not found in the working dir.
# That should allow maximum flexibility and stability for users.
def get_ref_file_path( inpath ):
    # Test for abs path or path in working dir.
    # If not found, return a path relative to the source dir.
    if os.path.isabs(inpath) or os.path.isfile(inpath):
        return inpath
    else:
        return os.path.join( workflow.basedir, '..', inpath )

# Specific build and tree:
# - BED file with haplogroup SNP positions
# - haplogroup info table
# - path to the tree file
# - name of the Y chromosome in the reference genome
REF_ID  = config["ref_data"]
if REF_ID not in config:
    raise ValueError(
        "Selected `ref_data: {REF_ID}` is not a valid value. "
        "Either use one of our pre-configured human references, "
        "or specify `ref_data: custom`, and provide your own."
    )

REF_SNPS = get_ref_file_path( config[REF_ID]["snps"] )
REF_INFO = get_ref_file_path( config[REF_ID]["info"] )
REF_TREE = get_ref_file_path( config[REF_ID]["tree"] )
CHROM    = get_ref_file_path( config[REF_ID]["chrom"] )
if not os.path.isfile(CHROM):
    # If the provided chrom is not a file,
    # we assume it to be a single chrom name,
    # and just reload the config entry.
    CHROM = config[REF_ID]["chrom"]

## --------------------------------------------------------------------------------
## helpers

unit_df = pd.read_table(config["units"], comment="#").set_index(["sampleId"])
SAMPLES = unit_df.index.values.tolist()

## --------------------------------------------------------------------------------
## functions

def get_bam(wildcards):
    return unit_df.loc[(wildcards.sample), "bam"]

## --------------------------------------------------------------------------------
## output file sets

callfiles = expand("calls/{sample}.calls", sample=SAMPLES)
yplacefiles = expand("yplace/{sample}.yplace", sample=SAMPLES)
aggfile = "aggregate.yplace"
aggplot = "aggregate.pdf"
scoretiesplot = "scoreties.pdf"

## --------------------------------------------------------------------------------
## targets

rule all:
    input:
        callfiles,
        yplacefiles,
        aggfile,
        aggplot,
        scoretiesplot

## --------------------------------------------------------------------------------
## rules

rule get_y_bam:
    input:
        get_bam
    output:
        "bam/Y.{sample}." + PREFIX + ".bam"
    params:
        regions=lambda wc: f"-L {CHROM}" if Path(CHROM).is_file() else CHROM
    conda:
        "envs/ybyra.yaml"
    shell:
        "samtools view -q{MQ} -F 4 -bh {input} {params.regions}  > {output}"

rule get_vcf:
    input:
        get_bam
    output:
        "vcf/Y.{sample}." + PREFIX + ".vcf.gz"
    params:
        sm=lambda wc: wc.sample,
        regions=lambda wc: f"-R {CHROM}" if Path(CHROM).is_file() else f"-r {CHROM}"
    conda:
        "envs/ybyra.yaml"
    shell:
        """
        echo -e {params.sm} > vcf/{params.sm}.samples.txt
        bcftools mpileup -B -q {MQ} -f {REF_GENOME} {params.regions} --ignore-RG {input} \
            | bcftools reheader -s vcf/{params.sm}.samples.txt \
            | bcftools call -Am -Oz --ploidy 1 > {output}
        """

rule index_vcf:
    input:
        "vcf/Y.{sample}." + PREFIX + ".vcf.gz"
    output:
        "vcf/Y.{sample}." + PREFIX + ".vcf.gz.tbi"
    conda:
        "envs/ybyra.yaml"
    shell:
        """
        bcftools index -t {input}
        """

rule get_alleles:
    input:
        vcf="vcf/Y.{sample}." + PREFIX + ".vcf.gz",
        tbi="vcf/Y.{sample}." + PREFIX + ".vcf.gz.tbi",
    output:
        "tables/Y.{sample}." + PREFIX + ".alleles.gz"
    conda:
        "envs/ybyra.yaml"
    shell:
        """
        bcftools query \
            -T {REF_SNPS} \
            -e 'TYPE=="indel"' \
            -f '%POS\t%REF\t%ALT\t%DP\t%QUAL\t%DP4\t[%TGT]\n' \
            {input.vcf} | gzip > {output}
        """

rule Ytree:
    input:
        alleles="tables/Y.{sample}." + PREFIX + ".alleles.gz"
    output:
       calls="calls/{sample}.calls",
       nopass="calls/{sample}.nopass",
    params:
       sm="{sample}",
       lib = lambda wildcards: config.get("lib_type", "both")
    conda:
        "envs/ybyra.yaml"
    shell:
        """
        python {workflow.basedir}/scripts/ytree.py \
            --lib {params.lib} \
            --alleles {input} \
            --out calls/{params.sm} \
            --snpinfo {REF_INFO}
        """

rule Yplace:
    input:
        calls="calls/{sample}.calls"
    output:
        "yplace/{sample}.yplace"
    params:
        damage = lambda wildcards: "--no-damage" if config.get("damage_filter", False) else ""
    conda:
        "envs/ybyra.yaml"
    shell:
        """
        python {workflow.basedir}/scripts/yplace.py \
            {params.damage} {REF_TREE} {input.calls} {output}
        """

rule aggregate_yplace:
    input:
        yplacefiles
    output:
        aggfile
    params:
        step_size = config["step_size"]
    conda:
        "envs/ybyra.yaml"
    shell:
        """
        python {workflow.basedir}/scripts/ysummary.py \
            {input} --step-size {params.step_size} > {output}
        """

rule plot_aggregate:
    input:
        aggfile
    output:
        "aggregate.pdf"
    conda:
        "envs/ybyra.yaml"
    shell:
        """
        export QT_QPA_PLATFORM=offscreen
        python {workflow.basedir}/scripts/yplot.py {input} {output}
        """

rule plot_scoreties:
    input:
        agg = aggfile
    output:
        "scoreties.pdf"
    conda:
        "envs/ybyra.yaml"
    shell:
        """
        export QT_QPA_PLATFORM=offscreen
        python {workflow.basedir}/scripts/yplot.py scoreties.yplace {output}
        """
